@echo off
echo Creating virtual environment...
python -m venv .venv

echo Activating virtual environment...
call .venv\Scripts\activate.bat

echo Installing dependencies...
pip install -r requirements.txt

echo Running migrations...
python manage.py migrate

echo Creating superuser (optional - you can skip this)...
python manage.py createsuperuser --noinput --username admin --email admin@example.com || echo Superuser creation skipped

echo Starting Django server...
python manage.py runserver

